import {
  ANGULAR_CMC_DEBUG_KEYS,
  GLOBAL_DEBUG_KEY_TO_JOINT,
  OPPOSITION_DEBUG_KEY,
} from "../../constants/debugKeys";

export { ANGULAR_CMC_DEBUG_KEYS, GLOBAL_DEBUG_KEY_TO_JOINT, OPPOSITION_DEBUG_KEY };

export const GONIOMETRY_EMIT_EPSILON = 1e-4;
