import {
  ANGULAR_CMC_DEBUG_KEYS,
  GLOBAL_DEBUG_KEY_TO_JOINT,
  OPPOSITION_DEBUG_KEY,
} from "../../constants/debugKeys";

export { ANGULAR_CMC_DEBUG_KEYS, GLOBAL_DEBUG_KEY_TO_JOINT, OPPOSITION_DEBUG_KEY };

export const GONIOMETRY_EMIT_EPSILON = 1e-4;
export const CMC_AUTOFRAME_KEYS = new Set(["TH_CMC_ABD", "TH_CMC_FLEX"]);

