export function buildOrderedAccordionsProps({
  poseState,
  poseActions,
  openPanel,
  onTogglePanel,
  onGlobalMode,
  onGrip,
  onClearPreset,
  onSetDebugKey,
  onClearDebugKey,
}) {
  return {
    state: {
      openPanel,
      thumb: poseState.thumb,
      thumbGoniometry: poseState.thumbGoniometry,
      thumbClinical: poseState.thumbClinical,
      isExplorationMode: poseState.isExplorationMode,
      explorationKapandjiTarget: poseState.explorationKapandjiTarget,
      globalD2D5: poseState.globalD2D5,
      wrist: poseState.wrist,
      grip: poseState.grip,
      globalMode: poseState.globalMode,
    },
    actions: {
      onTogglePanel,
      onThumbVal: poseActions.setThumbVal,
      onThumbCmcInput: poseActions.setThumbCmcInput,
      onEnterOppositionExploration: poseActions.enterOppositionExploration,
      onUpdateOppositionExploration: poseActions.updateOppositionExploration,
      onRestoreUserInputData: poseActions.restoreUserInputData,
      onExitOppositionExploration: poseActions.exitOppositionExploration,
      onUpdateGlobalD2D5: poseActions.updateGlobalD2D5,
      onWrist: poseActions.setWrist,
      onGlobalMode,
      onGrip,
    },
    ui: {
      onThumbHighlight: onSetDebugKey,
      onGlobalHighlight: onSetDebugKey,
      onWristHighlight: onSetDebugKey,
      onThumbClearHighlight: onClearDebugKey,
      onGlobalClearHighlight: onClearDebugKey,
      onThumbClearPreset: onClearPreset,
      onGlobalClearPreset: onClearPreset,
      onWristClearPreset: onClearPreset,
    },
  };
}
