export const GLOBAL_MCP_DEBUG_KEY = "GLOBAL_MCP";
export const GLOBAL_PIP_DEBUG_KEY = "GLOBAL_PIP";
export const GLOBAL_DIP_DEBUG_KEY = "GLOBAL_DIP";

export const TH_CMC_ABD_DEBUG_KEY = "TH_CMC_ABD";
export const TH_CMC_FLEX_DEBUG_KEY = "TH_CMC_FLEX";
export const OPPOSITION_DEBUG_KEY = "TH_CMC_OPP";

export const GLOBAL_DEBUG_KEY_TO_JOINT = {
  [GLOBAL_MCP_DEBUG_KEY]: "MCP",
  [GLOBAL_PIP_DEBUG_KEY]: "PIP",
  [GLOBAL_DIP_DEBUG_KEY]: "DIP",
};

export const ANGULAR_CMC_DEBUG_KEYS = new Set([TH_CMC_FLEX_DEBUG_KEY, TH_CMC_ABD_DEBUG_KEY]);
